### ISSUE TITLE
uk for Ukraine doesnt right!

### ISSUE THREAD

**Issue by VinceCamuto** [ashtokalo/php-translit#2]
uk - Ukrainian cyrillic chars!! wtf
uk - its United Kingdom (England)
ua - it is Ukraine

**Comment by ashtokalo** [comment]
Please read about ISO 639 is a set of standards by the International Organization for Standardization that is concerned with representation of names for language and language groups. You can check the Ukrainian language here https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes, see column ISO 639-1.

At same time you can search for ISO 3166, it's standard for country names, and ISO 3166-1 describes codes like UA for Ukraine and UK for United Kingdom.
